### PR TITLE
Use the new probot package @probot/get-private-key

### PR DESCRIPTION
**Pull request by KinnersleyM**
Prior to this change, errors would occur when trying to access the old helper file. Probot no longer includes this helper file.

This change adds the new package to make it compatible with the latest version of Probot.

Also updates README with more information on setting this up with environment variables.

-----
[View rendered README.md](https://github.com/KinnersleyM/serverless-lambda/blob/kinnersleym/fix-get-private-key/README.md)

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -11,7 +11,7 @@ const loadProbot = (appFn) => {
     new Probot({
       id: process.env.APP_ID,
       secret: process.env.WEBHOOK_SECRET,
-      privateKey: findPrivateKey(),
+      privateKey: getPrivateKey(),
```
Comment (gr2m) [inline index.js:14]: how would you usually configure the private key on lambda? I assume you wouldn't upload a `*.pem` file, so the only option really is to define the `PRIVATE_KEY` option? I think I'd remove the `getPrivateKey` method altogether and instead set

```suggestion
      privateKey: process.env.PRIVATE_KEY,
```

Comment (KinnersleyM) [reply index.js:14]: Given that `getPrivateKey()` does return `process.env.PRIVATE_KEY` as one of it's options and in the README there is a bit about using a `.pem`, I figured it would be safer to use this new package. But you're right, whenever I use lambda with serverless, I use the `serverless-dotenv-plugin` with `.env` files.

I can't say for a fact it is impossible to use a `*.pem` so I thought this would give a bit of flexibility. As things stand, this package is unusable with the latest `@probot` which is the reason for this PR.

**Comment by matushorvath** [comment]
I can confirm this is causing issues after updating the probot package to 10.17.1:
```json
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'probot/lib/helpers/get-private-key'\nRequire stack:\n- /var/task/node_modules/@probot/serverless-lambda/index.js\n- /var/task/bin/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'probot/lib/helpers/get-private-key'",
        "Require stack:",
        "- /var/task/node_modules/@probot/serverless-lambda/index.js",
        "- /var/task/bin/index.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:1015:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)",
        "    at Module.load (internal/modules/cjs/loader.js:879:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:724:14)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}
```

File: index.js (hunk 1 above)
Comment (gr2m) [reply index.js:14]: > As things stand, this package is unusable with the latest `@probot` which is the reason for this PR.

I agree, let's merge this PR and make a follow up PR for further discussion

**Review by gr2m — APPROVED** [review]
